name: Deploy - Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ vars.PROJECT_ID }}
          workload_identity_provider: ${{ vars.SECRET_WIP_NAME }}
          service_account: ${{ vars.PROVIDER_SA_EMAIL }}

      - name: Apply Terraform
        run: |
          terraform -chdir=iac/environments/dev init -backend-config="bucket=${{ vars.TF_BUCKET_NAME }}"
          terraform -chdir=iac/environments/dev plan
